WebComic_Rating_Service/config/routes.rb
Rails.application.routes.draw do
  resources :comics

end

WebComic_Rating_Service/app/models/comic.rb
class Comic < ActiveRecord::Base
end

WebComic_Rating_Service/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

WebComic_Rating_Service/app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  before_action :set_comic, only: [:show, :edit, :update, :destroy]

  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
  end

  # GET /comics/new
  def new
    @comic = Comic.new
  end

  # GET /comics/1/edit
  def edit
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(comic_params)

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render :show, status: :created, location: @comic }
      else
        format.html { render :new }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comics/1
  # PATCH/PUT /comics/1.json
  def update
    respond_to do |format|
      if @comic.update(comic_params)
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { render :show, status: :ok, location: @comic }
      else
        format.html { render :edit }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic.destroy
    respond_to do |format|
      format.html { redirect_to comics_url, notice: 'Comic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comic
      @comic = Comic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comic_params
      params.require(:comic).permit(:name, :author, :url, :synopsis, :genre, :rating_art, :rating_story, :rating_overall)
    end
end

WebComic_Rating_Service/app/helpers/application_helper.rb
module ApplicationHelper
end

WebComic_Rating_Service/app/helpers/comics_helper.rb
module ComicsHelper
end

WebComic_Rating_Service/app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_field :synopsis %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :rating_art %><br>
    <%= f.number_field :rating_art %>
  </div>
  <div class="field">
    <%= f.label :rating_story %><br>
    <%= f.number_field :rating_story %>
  </div>
  <div class="field">
    <%= f.label :rating_overall %><br>
    <%= f.number_field :rating_overall %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

WebComic_Rating_Service/app/views/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

WebComic_Rating_Service/app/views/comics/index.html.erb
<h1>Listing comics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Url</th>
      <th>Synopsis</th>
      <th>Genre</th>
      <th>Rating art</th>
      <th>Rating story</th>
      <th>Rating overall</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comics.each do |comic| %>
      <tr>
        <td><%= comic.name %></td>
        <td><%= comic.author %></td>
        <td><%= comic.url %></td>
        <td><%= comic.synopsis %></td>
        <td><%= comic.genre %></td>
        <td><%= comic.rating_art %></td>
        <td><%= comic.rating_story %></td>
        <td><%= comic.rating_overall %></td>
        <td><%= link_to 'Show', comic %></td>
        <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
        <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comic', new_comic_path %>

WebComic_Rating_Service/app/views/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

WebComic_Rating_Service/app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comic.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comic.author %>
</p>

<p>
  <strong>Url:</strong>
  <%= @comic.url %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @comic.synopsis %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @comic.genre %>
</p>

<p>
  <strong>Rating art:</strong>
  <%= @comic.rating_art %>
</p>

<p>
  <strong>Rating story:</strong>
  <%= @comic.rating_story %>
</p>

<p>
  <strong>Rating overall:</strong>
  <%= @comic.rating_overall %>
</p>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

WebComic_Rating_Service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebComicRatingService</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>